import Head from 'next/head'
import Image from 'next/image'
import styles from './home/style.module.scss'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/floatingdots.svg" id={styles.tr} className={styles.floatingDots} />
        <img src="/floatingdots.svg" id={styles.bl} className={styles.floatingDots} />
        <nav className={styles.nav}>
          <h1>Memories on Chain</h1>
          <button className={styles.walletConnect}> <img src="/metamask.svg" alt="" /> 0xd8...46de</button>
        </nav>
        <div className={styles.hero}>
          <div className={styles.heroText}>
            <h1>Engrave your memories forever on chain 💜</h1>
            <p>capture the moments & mint them as memories</p>
            <span className={styles.buttonCon}>
              <button className={styles.primaryBtn}>Connect Wallet</button>
              <button className={styles.secondaryBtn}>Explore Your Memories</button>
            </span>
          </div>
          <img className={styles.heroImg} src="/heroimg.png" alt="" />
        </div>
      </main>
    </div>
  )
}
